-
  name: Copy file to target servers
  hosts: all
  tasks:
    - name: copy file
      copy:
        src: /home/osboxes/Ansible_Demo_Excercise/test-file.txt
        dest: /home/osboxes/Ansible_Demo_Excercise/test-file.txt
